application: querocomergostoso
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  static_files: static/index.html
  upload: static/index.html
  
- url: /(.*\.html)$
  static_files: static/\1
  upload: static/.*\.html$

- url: /css
  static_dir: static/css
- url: /fonts
  static_dir: static/fonts
- url: /img
  static_dir: static/img
- url: /js
  static_dir: static/js

- url: /dalton
  script: main.app

- url: /api/restaurant
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
